name: deploy-resource
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout respository
        uses: actions/checkout@v3

      - name: Echo Script
        run: echo starting bicep

      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy bicep script
        uses: azure/arm-deploy@v1
        with: 
          resourceGroupName: dev-shop-rg
          template: main.bicep


      # - name: Install Bicep CLI
      #   run: |
      #     curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
      #     chmod +x ./bicep
      #     sudo mv ./bicep /usr/local/bin/bicep
      # - name: Build & deploy az resource
      #   run: |
      #     bicep build main.bicep
      #     az deployment sub create --name git-actions-worflow --location eastus2 --template-file main.bicep




